"use client";

import { Check, Copy, Code as FileCode2 } from "reicon-react";
import { useEffect, useState } from "react";
import { codeToHtml } from "shiki";
import { Button } from "@/components/ui/button";
import "./code-block.css";
import { useTheme } from "next-themes";

const LANG_ALIAS: Record<string, string> = {
  typescript: "ts",
  javascript: "js",
  sql: "sql",
  prisma: "prisma",
};

interface SyntaxHighlightProps {
  code: string;
  language: string;
  filename: string;
}

export function SyntaxHighlight({
  code,
  language,
  filename,
}: SyntaxHighlightProps) {
  const [html, setHtml] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);

  const { resolvedTheme } = useTheme();

  useEffect(() => {
    let cancelled = false;
    const lang = LANG_ALIAS[language] ?? language;
    codeToHtml(code, { lang, theme: `github-${resolvedTheme}` })
      .then((h) => {
        if (!cancelled) setHtml(h);
      })
      .catch(() => {
        if (!cancelled) setHtml(null);
      });
    return () => {
      cancelled = true;
    };
  }, [code, language]);

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(code);
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    } catch {
      // clipboard unavailable
    }
  };

  return (
    <div className="code-block max-w-xl w-full overflow-hidden rounded-xl border border-border">
      <div className="flex min-w-0 items-center justify-between gap-2 border-b border-border bg-muted/50 px-3 py-2">
        <span className="flex min-w-0 items-center gap-1.5 text-xs font-medium text-muted-foreground">
          <FileCode2 className="size-3.5 shrink-0 text-muted-foreground" />
          <span className="truncate">{filename}</span>
        </span>

        <Button
          size="icon-sm"
          variant="ghost"
          onClick={handleCopy}
          aria-label="Copy code"
          className="h-6 w-6 shrink-0 text-muted-foreground"
        >
          {copied ? (
            <Check className="size-3.5 text-emerald-600" />
          ) : (
            <Copy className="size-3.5" />
          )}
        </Button>
      </div>

      {html ? (
        <div
          className="min-w-0 max-w-full overflow-x-auto overflow-y-auto"
          /* biome-ignore lint/security/noDangerouslySetInnerHtml: html is generated by shiki from escaped code; no user-controlled markup */
          dangerouslySetInnerHTML={{ __html: html }}
        />
      ) : (
        <pre className="min-w-0 max-w-full overflow-x-auto p-4 font-mono text-xs leading-relaxed text-foreground">
          <code>{code}</code>
        </pre>
      )}
    </div>
  );
}
