import type { Field, SchemaProject, Table } from "../../domain";
import type { SchemaAdapter } from "../adapter.interface";

const MONGODB_TYPE: Record<string, string> = {
  string: "String",
  text: "String",
  integer: "Number",
  bigint: "Long",
  float: "Number",
  double: "Number",
  decimal: "Decimal128",
  boolean: "Boolean",
  date: "Date",
  timestamp: "Date",
  json: "Mixed",
  uuid: "String",
  binary: "Buffer",
};

function mongooseType(field: Field): string {
  return MONGODB_TYPE[field.type] ?? "String";
}

function schemaName(name: string): string {
  const pascal = name
    .split(/[^A-Za-z0-9]/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
  return /^[A-Za-z]/.test(pascal) ? pascal : `M${pascal}`;
}

function fieldDef(field: Field): string {
  const parts: string[] = [];
  if (field.primaryKey) {
    parts.push(`type: ${mongooseType(field)}, required: true, unique: true`);
    if (field.type === "uuid") parts.push("default: () => crypto.randomUUID()");
  } else {
    parts.push(`type: ${mongooseType(field)}`);
    if (field.isArray) parts.push("type: [String]");
    if (!field.nullable) parts.push("required: true");
    if (field.unique) parts.push("unique: true");
    if (field.defaultValue) parts.push(`default: ${field.defaultValue}`);
  }
  if (field.comment)
    parts.push(`description: "${field.comment.replaceAll('"', '\\"')}"`);
  return `  ${field.name}: {\n    ${parts.join(",\n    ")}\n  }`;
}

function buildSchema(table: Table): string {
  const name = schemaName(table.name);
  const fields = table.fields.map(fieldDef).join(",\n");
  const indexes = table.indexes
    .map((idx) => {
      const cols = idx.fieldIds
        .map((id) => `"${table.fields.find((f) => f.id === id)?.name}"`)
        .filter(Boolean)
        .join(", ");
      return `  schema.index({ ${cols} }${idx.unique ? ", { unique: true }" : ""})`;
    })
    .join("\n");

  const blocks: string[] = [];
  blocks.push(`const ${name}Schema = new Schema({`);
  blocks.push(fields);
  blocks.push("}, {");
  blocks.push("  timestamps: true,");
  blocks.push(`  collection: ${JSON.stringify(table.name)}`);
  blocks.push("})");
  if (indexes) blocks.push(indexes);
  blocks.push(
    `export const ${name} = models.${name} || model("${name}", ${name}Schema)`,
  );
  return blocks.join("\n");
}

export const mongodbAdapter: SchemaAdapter = {
  key: "mongodb",
  name: "MongoDB (Mongoose)",
  description: "Mongoose schema definitions for MongoDB",
  language: "javascript",
  extension: "js",
  mimeType: "text/javascript",
  supportsImport: false,

  export(project: SchemaProject): string {
    const header = [
      'import { Schema, model, models } from "mongoose"',
      "",
      "// MongoDB schema definitions — generated by SurfDB",
      "",
    ].join("\n");
    const schemas = project.tables.map(buildSchema).join("\n\n");
    return `${header + schemas}\n`;
  },

  import(_code: string): SchemaProject {
    throw new Error("MongoDB import is not supported yet");
  },
};
