import type { Field, SchemaProject, Table } from "../../domain";
import { normalizeRelationDirection } from "../../domain/services/schema.service";
import type { SchemaAdapter } from "../adapter.interface";
import { importMongooseSchema } from "./import";

const MONGODB_TYPE: Record<string, string> = {
  string: "String",
  text: "String",
  integer: "Number",
  bigint: "Long",
  float: "Number",
  double: "Number",
  decimal: "Schema.Types.Decimal128",
  boolean: "Boolean",
  date: "Date",
  timestamp: "Date",
  json: "Mixed",
  uuid: "String",
  binary: "Buffer",
};

function mongooseType(field: Field): string {
  return MONGODB_TYPE[field.type] ?? "String";
}

function schemaName(name: string): string {
  const pascal = name
    .split(/[^A-Za-z0-9]/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
  return /^[A-Za-z]/.test(pascal) ? pascal : `M${pascal}`;
}

function fieldKey(name: string): string {
  const cleaned = name.replace(/[^A-Za-z0-9_$]/g, "_");
  return /^\d/.test(cleaned) ? `_${cleaned}` : cleaned;
}

function formatMongooseDefault(field: Field): string | null {
  if (field.defaultValue == null) return null;
  const v = field.defaultValue.trim();
  if (
    v === "now" ||
    v === "NOW()" ||
    v === "now()" ||
    v === "CURRENT_TIMESTAMP"
  ) {
    return "Date.now";
  }
  if (/^-?\d+(\.\d+)?$/.test(v)) return v;
  if (v === "true" || v === "false") return v;
  if (v === "null") return "null";
  if (
    field.type === "string" ||
    field.type === "text" ||
    field.type === "uuid" ||
    field.type === "enum"
  ) {
    return `"${v.replaceAll('"', '\\"')}"`;
  }
  return `"${v.replaceAll('"', '\\"')}"`;
}

function fieldDef(
  field: Field,
  isFK: boolean,
  fkEntry?: { relatedModel: string; relatedFieldType: string },
): string {
  const parts: string[] = [];
  if (field.primaryKey) {
    const typeName = field.isArray
      ? `[${mongooseType(field)}]`
      : mongooseType(field);
    parts.push(`type: ${typeName}, required: true, unique: true`);
    if (field.type === "uuid") parts.push("default: () => crypto.randomUUID()");
  } else if (isFK && fkEntry) {
    const typeName = MONGODB_TYPE[fkEntry.relatedFieldType] ?? "String";
    parts.push(`type: ${typeName}`);
    parts.push(`ref: "${fkEntry.relatedModel}"`);
    if (!field.nullable) parts.push("required: true");
  } else {
    if (field.isArray) {
      parts.push(`type: [${mongooseType(field)}]`);
    } else {
      parts.push(`type: ${mongooseType(field)}`);
    }
    if (!field.nullable) parts.push("required: true");
    if (field.unique) parts.push("unique: true");
    if (field.type === "enum" && field.enumValues?.length) {
      const enumVals = field.enumValues.map((v) => `"${v}"`).join(", ");
      parts.push(`enum: [${enumVals}]`);
    }
    const dflt = formatMongooseDefault(field);
    if (dflt) parts.push(`default: ${dflt}`);
  }
  if (field.comment)
    parts.push(`description: "${field.comment.replaceAll('"', '\\"')}"`);
  return `  ${fieldKey(field.name)}: {\n    ${parts.join(",\n    ")}\n  }`;
}

function buildSchema(
  table: Table,
  fkInfo: Map<string, { relatedModel: string; relatedFieldType: string }>,
): string {
  const name = schemaName(table.name);
  const hasTimestamps = table.fields.some(
    (f) =>
      f.name === "created_at" ||
      f.name === "updated_at" ||
      f.name === "createdAt" ||
      f.name === "updatedAt",
  );
  const fields = table.fields
    .map((f) => {
      const info = fkInfo.get(f.id);
      return fieldDef(f, !!info, info);
    })
    .join(",\n");
  const indexes = table.indexes
    .map((idx) => {
      const cols = idx.fieldIds
        .map((id) => {
          const field = table.fields.find((f) => f.id === id);
          if (!field) return "";
          const direction = idx.type === "hash" ? "hashed" : "1";
          return `${fieldKey(field.name)}: ${direction}`;
        })
        .filter(Boolean)
        .join(", ");
      return `  ${name}Schema.index({ ${cols} }${idx.unique ? ", { unique: true }" : ""})`;
    })
    .join("\n");

  const blocks: string[] = [];
  blocks.push(`const ${name}Schema = new Schema({`);
  blocks.push(fields);
  blocks.push("}, {");
  if (hasTimestamps) blocks.push("  timestamps: true,");
  blocks.push(`  collection: ${JSON.stringify(table.name)}`);
  blocks.push("})");
  if (indexes) blocks.push(indexes);
  blocks.push(
    `export const ${name} = models.${name} || model("${name}", ${name}Schema)`,
  );
  return blocks.join("\n");
}

export const mongodbAdapter: SchemaAdapter = {
  key: "mongodb",
  name: "MongoDB (Mongoose)",
  description: "Mongoose schema definitions for MongoDB",
  language: "javascript",
  extension: "js",
  mimeType: "text/javascript",
  supportsImport: true,

  export(project: SchemaProject): string {
    const header = [
      'import mongoose, { Schema, model, models } from "mongoose"',
      "",
      "// MongoDB schema definitions — generated by SurfDB",
      "",
    ].join("\n");

    const normalized = normalizeRelationDirection(project);

    const fkInfo = new Map<
      string,
      { relatedModel: string; relatedFieldType: string }
    >();
    for (const rel of normalized.relations) {
      const sourceTable = normalized.tables.find(
        (t) => t.id === rel.sourceTableId,
      );
      const targetTable = normalized.tables.find(
        (t) => t.id === rel.targetTableId,
      );
      if (!sourceTable || !targetTable) continue;
      const sourceField = sourceTable.fields.find(
        (f) => f.id === rel.sourceFieldId,
      );
      const targetField = targetTable.fields.find(
        (f) => f.id === rel.targetFieldId,
      );
      if (!sourceField) continue;
      fkInfo.set(sourceField.id, {
        relatedModel: schemaName(targetTable.name),
        relatedFieldType: targetField?.type ?? "string",
      });
    }

    const schemas = normalized.tables
      .map((table) => buildSchema(table, fkInfo))
      .join("\n\n");
    return `${header}${schemas}\n`;
  },

  import(code: string): SchemaProject {
    return importMongooseSchema(code);
  },
};
